# Generated by Django 5.1.4 on 2024-12-19 05:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SME', '0003_alter_sellerproduct_options_company_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offered_by', to='SME.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number, including country code.')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional profile picture for the user.', upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('admin', 'Admin'), ('supplier', 'Supplier')], default='seller', help_text='Role of the user in the system.', max_length=10, verbose_name='User Role'),
        ),
    ]
